// Code generated by "stringer -type=WindowPosition"; DO NOT EDIT.

package entity

import "strconv"

const _WindowPosition_name = "WPTopWPMiddleWPBottom"

var _WindowPosition_index = [...]uint8{0, 5, 13, 21}

func (i WindowPosition) String() string {
	i -= 3
	if i < 0 || i >= WindowPosition(len(_WindowPosition_index)-1) {
		return "WindowPosition(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _WindowPosition_name[_WindowPosition_index[i]:_WindowPosition_index[i+1]]
}
