// Code generated by "stringer -type=WindowColor"; DO NOT EDIT.

package entity

import "strconv"

const _WindowColor_name = "WCWindowWCDarkWCTransparent"

var _WindowColor_index = [...]uint8{0, 8, 14, 27}

func (i WindowColor) String() string {
	if i < 0 || i >= WindowColor(len(_WindowColor_index)-1) {
		return "WindowColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WindowColor_name[_WindowColor_index[i]:_WindowColor_index[i+1]]
}
